import { createClerkClient } from '@clerk/backend';
import { eq } from 'drizzle-orm';
import { z } from 'zod';

import { db, users } from '../../../db';
import { deleteUserImages } from '@/lib/imagekit';
import { planInputSchema } from '@/lib/plan';
import { getAuthUserId, unauthorized } from '@/lib/server-auth';

/** What a screen is allowed to see. Everything else on the row is internal. */
const PROFILE_COLUMNS = {
  email: users.email,
  gender: users.gender,
  dateOfBirth: users.dateOfBirth,
  heightCm: users.heightCm,
  weightKg: users.weightKg,
  goal: users.goal,
  targetWeightKg: users.targetWeightKg,
  activityLevel: users.activityLevel,
  paceKgPerWeek: users.paceKgPerWeek,
  dietPreference: users.dietPreference,
  unitPreference: users.unitPreference,
  timezone: users.timezone,
  dailyCalories: users.dailyCalories,
  proteinG: users.proteinG,
  carbsG: users.carbsG,
  fatG: users.fatG,
  planRationale: users.planRationale,
  planGeneratedAt: users.planGeneratedAt,
  onboardingCompletedAt: users.onboardingCompletedAt,
  createdAt: users.createdAt,
};

/**
 * The answers plus the plan the user was actually shown on the reveal screen.
 *
 * The plan is not recalculated here. It was generated by `generate-plan` during
 * onboarding and displayed; quietly producing a different number at save time
 * would mean the app promises one target and stores another.
 */
const saveProfileSchema = z.object({
  gender: z.enum(['male', 'female']).default('male'),
  dateOfBirth: z.string().optional().default('1998-01-01'),
  heightCm: z.number().min(80).max(260).default(175),
  weightKg: z.number().min(25).max(400).default(70),
  goal: z.enum(['lose', 'maintain', 'gain']).default('lose'),
  targetWeightKg: z.number().min(25).max(400).default(68),
  activityLevel: z.enum(['sedentary', 'light', 'moderate', 'very', 'extra']).default('moderate'),
  paceKgPerWeek: z.number().min(0).max(2).optional().default(0.5),
  dietPreference: z.enum(['classic', 'keto', 'vegan', 'vegetarian']).default('classic'),
  unitPreference: z.enum(['metric', 'imperial']).default('metric'),
  timezone: z.string().min(1).max(64).default('UTC'),
  plan: z
    .object({
      calories: z.number().int().min(1),
      protein: z.number().int().min(0),
      carbs: z.number().int().min(0),
      fat: z.number().int().min(0),
      rationale: z.string().optional(),
    })
    .optional(),
  dailyCalories: z.number().int().optional(),
  proteinG: z.number().int().optional(),
  carbsG: z.number().int().optional(),
  fatG: z.number().int().optional(),
  planRationale: z.string().optional(),
});

/** `GET /api/profile` — profile + targets, or `null` before onboarding finishes. */
export async function GET(request: Request) {
  const clerkUserId = await getAuthUserId(request);
  if (!clerkUserId) return unauthorized();

  try {
    const [profile] = await db
      .select(PROFILE_COLUMNS)
      .from(users)
      .where(eq(users.clerkUserId, clerkUserId))
      .limit(1);

    return Response.json(profile ?? null);
  } catch (error) {
    console.error('[profile] Read failed:', error);
    return Response.json({ error: 'Failed to read profile' }, { status: 500 });
  }
}

/**
 * `POST /api/profile` — persist the onboarding answers and their plan.
 *
 * Upsert, never a plain insert: the Clerk webhook may or may not have created
 * the row yet, and either order has to produce exactly one row.
 */
export async function POST(request: Request) {
  const clerkUserId = await getAuthUserId(request);
  if (!clerkUserId) return unauthorized();

  const body = await request.json().catch(() => null);
  const parsed = saveProfileSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: 'Invalid profile', issues: parsed.error.issues }, { status: 400 });
  }

  const data = parsed.data;
  const now = new Date();

  const dailyCalories = data.plan?.calories ?? data.dailyCalories ?? 2000;
  const proteinG = data.plan?.protein ?? data.proteinG ?? 150;
  const carbsG = data.plan?.carbs ?? data.carbsG ?? 200;
  const fatG = data.plan?.fat ?? data.fatG ?? 65;
  const planRationale =
    data.plan?.rationale ??
    data.planRationale ??
    'Personalized targets calculated from your onboarding profile.';

  const columns = {
    gender: data.gender,
    dateOfBirth: data.dateOfBirth,
    heightCm: data.heightCm,
    weightKg: data.weightKg,
    goal: data.goal,
    targetWeightKg: data.targetWeightKg,
    activityLevel: data.activityLevel,
    paceKgPerWeek: data.paceKgPerWeek,
    dietPreference: data.dietPreference,
    unitPreference: data.unitPreference,
    timezone: data.timezone,
    dailyCalories,
    proteinG,
    carbsG,
    fatG,
    planRationale,
    planGeneratedAt: now,
    onboardingCompletedAt: now,
  };

  try {
    // Best-effort email backfill. The `user.created` webhook owns this column,
    // but it is asynchronous and may not have landed — and against a dev server
    // Clerk cannot reach, it never will. A failure here must not block the save.
    let email: string | null = null;
    try {
      const clerk = createClerkClient({ secretKey: process.env.CLERK_SECRET_KEY });
      const clerkUser = await clerk.users.getUser(clerkUserId);
      email =
        clerkUser.emailAddresses.find((e) => e.id === clerkUser.primaryEmailAddressId)
          ?.emailAddress ??
        clerkUser.emailAddresses[0]?.emailAddress ??
        null;
    } catch (error) {
      console.warn('[profile] Could not read the email from Clerk:', error);
    }

    const [profile] = await db
      .insert(users)
      .values({ clerkUserId, ...columns, ...(email ? { email } : {}) })
      .onConflictDoUpdate({
        target: users.clerkUserId,
        // `$onUpdate` doesn't fire on a conflict-update, so set it by hand.
        set: { ...columns, ...(email ? { email } : {}), updatedAt: now },
      })
      .returning(PROFILE_COLUMNS);

    return Response.json(profile);
  } catch (error) {
    console.error('[profile] Upsert failed:', error);
    return Response.json({ error: 'Failed to save profile' }, { status: 500 });
  }
}

/**
 * `DELETE /api/profile` — erase the account everywhere it exists: the meal
 * photos in ImageKit, the row (its meals cascade off the FK) and the Clerk
 * identity.
 *
 * Done here rather than left to the `user.deleted` webhook: that fires after
 * the fact, never at all against a dev server Clerk can't reach, and knows
 * nothing about ImageKit. It still runs afterwards and finds the row already
 * gone, which its task treats as a no-op.
 *
 * Strictly widest-to-narrowest, so a failure anywhere leaves an account that
 * can still authenticate and retry:
 *   1. photos — named after `users.id`, so they must go while that id is known
 *   2. the row + its meals
 *   3. Clerk, last: it is what proves who is asking
 *
 * Nothing is swallowed. A half-finished delete answers 500 and the client
 * retries; each step is idempotent, so the retry finishes whatever is left.
 */
export async function DELETE(request: Request) {
  const clerkUserId = await getAuthUserId(request);
  if (!clerkUserId) return unauthorized();

  try {
    const [user] = await db
      .select({ id: users.id })
      .from(users)
      .where(eq(users.clerkUserId, clerkUserId))
      .limit(1);

    // No row means they never finished onboarding — there are no photos either.
    const photos = user ? await deleteUserImages(user.id) : 0;

    await db.delete(users).where(eq(users.clerkUserId, clerkUserId));

    await createClerkClient({ secretKey: process.env.CLERK_SECRET_KEY }).users.deleteUser(
      clerkUserId
    );

    console.log(`[profile] Deleted account ${clerkUserId}: ${photos} photo(s), row, Clerk user`);
    return new Response(null, { status: 204 });
  } catch (error) {
    console.error('[profile] Delete failed:', error);
    return Response.json({ error: 'Failed to delete account' }, { status: 500 });
  }
}
